// Turning a quote into an Office Script.
//
// With no app registration there is no Microsoft Graph, so the app cannot write
// the workbook itself. It writes the script instead: you open your copy of the
// client's template in Excel on the web, paste this in once, and run it. Excel
// does the writing, which is the whole point. A library that re-saved the file
// would quietly drop the INDIRECT dropdowns and the structured tables the form
// depends on; Excel writing into its own file drops nothing.
//
// Office Scripts need no administrator and no app registration. They are on by
// default and are included with the business Microsoft 365 plans.

import type { HighlightUpdate } from './tracker';
import type { CellWrite } from './template';

/** JSON-encode a value the way TypeScript source wants it. */
function lit(v: string | number | boolean): string {
  return typeof v === 'string' ? JSON.stringify(v) : String(v);
}

/**
 * A self-contained Office Script that fills one quote into the open workbook.
 * The values are baked in, so there is nothing to paste separately and nothing
 * to keep in step.
 */
export function buildOfficeScript(writes: CellWrite[], fileName: string): string {
  const rows = writes
    .map((w) => `  { sheet: ${lit(w.sheet)}, cell: ${lit(w.address)}, value: ${lit(w.value)}${w.numberFormat ? `, format: ${lit(w.numberFormat)}` : ''} },`)
    .join('\n');

  return `/**
 * Fills ${fileName}
 * Generated by Quote Desk. ${writes.length} cells.
 *
 * How to use this, once per quote:
 *   1. In SharePoint or OneDrive, make a copy of the blank client template and
 *      rename the copy to the file name above.
 *   2. Open that copy in Excel on the web (not the desktop app).
 *   3. Automate > New Script, delete what is there, paste this in, press Run.
 *   4. Check the totals on the sheet against the ones the app showed you.
 *
 * It only writes the cells listed below. It does not add, remove or re-save
 * anything else, so the dropdowns, tables and hidden sheets stay as they are.
 */
function main(workbook: ExcelScript.Workbook) {
  const writes: { sheet: string; cell: string; value: string | number | boolean; format?: string }[] = [
${rows}
  ];

  let written = 0;
  const missing: string[] = [];
  for (const w of writes) {
    const sheet = workbook.getWorksheet(w.sheet);
    if (!sheet) {
      if (missing.indexOf(w.sheet) === -1) missing.push(w.sheet);
      continue;
    }
    const range = sheet.getRange(w.cell);
    range.setValue(w.value);
    if (w.format) range.setNumberFormatLocal(w.format);
    written++;
  }

  if (missing.length) {
    console.log("These sheets were not found, so nothing was written to them: " + missing.join(", "));
    console.log("Check you opened a copy of the client's template and not another workbook.");
  }
  console.log("Wrote " + written + " of " + writes.length + " cells.");
}
`;
}

/**
 * A script that re-highlights the office tracker to match the board.
 *
 * The same reasoning as the quote export: Excel does the writing, so nothing
 * else in the spreadsheet is touched. It only sets the fill colour of the rows
 * listed, and running it again when nothing has moved changes nothing.
 */
export function buildTrackerScript(sheetName: string, updates: HighlightUpdate[], lastColumn = 'I'): string {
  const rows = updates.map((u) => `  { row: ${u.row}, colour: ${JSON.stringify(`#${u.colour}`)} }, // ${u.workOrder}: ${u.because}`).join('\n');
  return `/**
 * Brings the tracker's highlighting up to date with the quote board.
 * Generated by Quote Desk. ${updates.length} row${updates.length === 1 ? '' : 's'}.
 *
 * To run it: open the tracker in Excel on the web, Automate > New Script,
 * paste this in, press Run. It only changes the fill colour of the rows below.
 * Nothing else in the workbook is touched, and running it twice is harmless.
 */
function main(workbook: ExcelScript.Workbook) {
  const sheet = workbook.getWorksheet(${JSON.stringify(sheetName)});
  if (!sheet) {
    console.log("No sheet called ${sheetName} in this workbook. Nothing was changed.");
    return;
  }

  const updates: { row: number; colour: string }[] = [
${rows}
  ];

  for (const u of updates) {
    sheet.getRange("A" + u.row + ":${lastColumn}" + u.row).getFormat().getFill().setColor(u.colour);
  }
  console.log("Re-coloured " + updates.length + " row(s).");
}
`;
}
